src/TimeProfiler.php
- Pour un `composer phing`, on set le `max_time` a tres grand
=> [FEATURE#22352] Soucis avec phing avec le TimeProfiler

src/RabbitMQ.php
- Changement de l'initialisation du client de rabbitmq, sorry
=> [FIX#21027] Apparemment mes changements ont pété rabbitmq

.gitignore, composer.json, composer.lock
- Modification du composer.json pour ne plus fixer la version de behat
- On versionne le composer .lock
=> [FEATURE#25012] Version Behat

README.md, src/ApiContext.php, src/AuthContext.php, src/BaseContext.php, src/CoverageContext.php, src/DoctrineContext.php, src/ElasticContext.php, src/FixedDateContext.php, src/MainContext.php, src/RabbitContext.php, src/ServerContext.php, src/SvnContext.php, src/TimeProfilerContext.php, src/contexts/ApiContext.php
=> Ajout de steps génériques pour les test API

src/ApiContext.php, src/BaseContext.php, src/MainContext.php, src/RabbitContext.php
- Ajout de backslash devant les exceptions
=> [FEATURE#27411] Namespace and exceptions

src/FixedDateContext.php
On passe FixedTime en beforeSuite pour qu'il passe avant le contexte elasticsearch.
=> [FIX#28659] FixedTime en beforeSuite

src/CoverageContext.php, src/RabbitContext.php
- Fix RabbitContext
- Ajout de use pour le CoverageContext
=> Fix/28659 Fix RabbitContext

composer.json
- Php unit et coverage en require-dev
=> [FIX#28659] Require-dev

src/RabbitContext.php
- On passe par la conf pour créer le client RabbitMq
- Utilisation de GuzzleHttp
=> [FIX#28659] Modification de la création du client

src/ApiContext.php
Ajout d'un fonction de comparaison de csv
=> [FIX#28659] Ajout d'une fonction de comparaison de csv

src/ApiContext.php, src/AuthContext.php
- Ajout d'une step d'upload de fichiers dans ApiContext
- Fix du AuthContext qui écrasait la request en afterstep
=> [FIX#28659] ApiContext::uploadFile + fix AuthContext

src/ApiContext.php, src/RabbitContext.php
- On utilise la méthode check pour vérifier le contenu des jobs rmq
- Déplacement de fonction de RabbitContext vers ApiContext
=> [FIX#33096] Utilisation de check pour les jobs

src/RabbitContext.php
- Ajout d'une step de publication via un producer
- Ajout d'une step de consume via un consumer
=> [FIX#33096] Ajout de steps rabbitmq

composer.json, composer.lock, src/AuthContext.php, src/DoctrineContext.php, src/FixedDateContext.php
La traduction des keyword dans Gherkin a évolué.
`Étant donné que` est désormais pris en compte, (anciennement `Étant donné`). Il faut donc modifier les définitions des steps pour prendre en compte ce changement.
=> [FEATURE#35176] Modification keyword Gherkin

src/AuthContext.php, src/DoctrineContext.php, src/FixedDateContext.php, src/RabbitContext.php
- Merci la personne qui a merge
=> [FIX#27775] Petit oubli

src/ApiContext.php, src/RabbitContext.php
- Des méthodes utiles pour tous les tests
=> [Feature/33794] Ajout de méthode réutilisable partout

src/ApiContext.php
C'est comme pour les images mais avec des PDF
=> [FEATURE#37352] Ajout d'un check MD5 pour les PDF

src/RabbitContext.php
=> [FEATURE#33794] Changement du rabbitcontext

src/ApiContext.php
On garde les cookies de la reponse
=> [FEATURE#33186] Ajout des cookies parce qu'on peut vouloir les tester

src/ApiContext.php
Ca doit pouvoir se modifier aussi :)
=> [FEATURE#33186] Ajout de la possiblité de parametrer la base_url

src/AuthContext.php
Ajout d'une step pour tester le logas sur behat v2.
=> [FEATURE#56754] Ajout d'une step logas

README.md, composer.json, composer.lock, src/HttpApiMockContext.php
On ajoute un context de mock au behat-utils pour pouvoir utiliser les steps liés au proxy sur nos APIs.
=> [Feature/76038] Ajout du context pour les tests mock sur proxy

src/RabbitContext.php
Maintenant on peut s'assurer que le code n'a rien publié
=> Ajout d'une step la queue devrait etre vide

src/HttpApiMockContext.php
=> Ajout de la possibilité de retourner des JPEG avec le mock http

src/DoctrineContext.php
On ajoute le Doctrine context refactorisé.
=> Feature/133499 Ajout du Doctrine context

src/ApiContext.php, src/CommandContext.php, src/DoctrineContext.php, src/ElasticContext.php
On modifie les methodes `dump` et `indexElasticsearch`, on fait maintenant appel à des commandes pour faire le boulot.
Ajout du CommandContext pour les tests.
=> Feature/133499 Update Du behat utils

src/ApiContext.php, src/TimeProfilerContext.php
On se base uniquement sur l'appel à l'application plutôt qu'a tout le scénario
=> Amélioration de la précision du time profiler

src/RabbitContext.php
On reset le compteur pour ne pas tomber dans d'affreux travers
=> [HF] Improvement du consume de jobs
